---
# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7
          ports:
            - containerPort: 27017
              name: mongodb
          env:
            - name: MONGO_INITDB_DATABASE
              value: "risklens"
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: mongodb-data
          hostPath:
            path: /mnt/instana/stanctl/objects/mongodb-data
            type: DirectoryOrCreate

---
# MongoDB Service
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      protocol: TCP

---
# Python API Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
  labels:
    app: python-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      initContainers:
      - name: wait-for-mongodb
        image: busybox
        command: ['sh', '-c', 'until nc -z mongodb 27017; do echo waiting; sleep 2; done']

      containers:
        - name: python-api
          image: ghcr.io/vinaycharlie01/local-llama-agent-python:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          env:
            # API Configuration
            - name: API_HOST
              value: "0.0.0.0"
            - name: API_PORT
              value: "8000"
            # MongoDB Configuration
            - name: MONGO_HOST
              value: "mongodb"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DB
              value: "risklens"
            # Masumi Configuration
            - name: NETWORK
              value: "Preprod"
            - name: PAYMENT_AMOUNT
              value: "1000000"
            - name: PAYMENT_UNIT
              value: "16a55b2a349361ff88c03788f93e1e966e5d689605d044fef722ddde0014df10745553444d"
            # Secrets from Secret resource
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: masumi-secrets
                  key: payment_server_url
            - name: PAYMENT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: masumi-secrets
                  key: payment_api_key
            - name: AGENT_IDENTIFIER
              valueFrom:
                secretKeyRef:
                  name: masumi-secrets
                  key: agent_identifier
            - name: SELLER_VKEY
              valueFrom:
                secretKeyRef:
                  name: masumi-secrets
                  key: seller_vkey
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: masumi-secrets
                  key: openai_api_key
            - name: BLOCKFROST_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: masumi-secrets
                  key: blockfrost_project_id
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
      imagePullSecrets:
        - name: ghcr-secret

---
# Python API Service
apiVersion: v1
kind: Service
metadata:
  name: python-api
  labels:
    app: python-api
spec:
  type: ClusterIP
  selector:
    app: python-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your-real-email@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-api-ingress
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    # Disable SSL redirect to allow HTTP-01 challenge
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: app.vinayai.co.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: python-api
                port:
                  number: 80
  tls:
    - hosts:
        - app.vinayai.co.in
      secretName: python-api-tls

